
var BgDefine = [
        {   name:"HJZL",
            sakura:true,
            plist:"res/background_jp/",
            fore:{img:"res/bg/hjzl/hjzl_fore.png",pos:cc.p(0,385)},
            back:{img:"res/bg/hjzl/hjzl_back.png",pos:cc.p(0,385)},
            layerScale:[-0.15,0,0,0.15,0.28,0.45],
            lists:[
                [
					{img:"#hjzl_1.png"},
					{img:"#hjzl_2.png"},
					{img:"#hjzl_3.png"},
					{img:"#hjzl_4.png"},
					{img:"#hjzl_6.png"},
					{img:"#hjzl_7.png"},
					{img:"#hjzl_8.png"},
					{img:"#hjzl_9.png"},
					{img:"#hjzl_11.png"},
					{img:"#hjzl_12.png"},	
					{img:"#hjzl_13.png"},
					{img:"#hjzl_14.png"},
					{img:"#hjzl_15.png"},
					{img:"#hjzl_16.png"},
					{img:"#hjzl_17.png"},
					{img:"#hjzl_18.png"},
					{img:"#hjzl_19.png"},
					{img:"#hjzl_20.png"},
					{img:"#hjzl_21.png"},
					{img:"#hjzl_22.png"},
					{img:"#hjzl_23.png"},
					{img:"#hjzl_24.png"},	
    			],     
                [     
					{img:"#hjzl_25.png"},
					{img:"#hjzl_26.png"},
					{img:"#hjzl_27.png"},
					{img:"#hjzl_29.png"},
					{img:"#hjzl_31.png"},
					{img:"#hjzl_32.png"},
					{img:"#hjzl_34.png"},
					{img:"#hjzl_35.png"},
					{img:"#hjzl_36.png"},	
					{img:"#hjzl_37.png"},
					{img:"#hjzl_40.png"},
					{img:"#hjzl_41.png"},
					{img:"#hjzl_42.png"},
					{img:"#hjzl_43.png"},
					{img:"#hjzl_44.png"},
					{img:"#hjzl_45.png"},
					{img:"#hjzl_48.png"},	
                ],         
                [          
					//					{img:"#res/bg/hjzl/hjzl_50.png"},
					//					{img:"#res/bg/hjzl/hjzl_51.png"},
					//					{img:"#res/bg/hjzl/hjzl_52.png"},
					{img:"#hjzl_53.png"},
					{img:"#hjzl_54.png"},
					{img:"#hjzl_55.png"},
					{img:"#hjzl_56.png"},
					{img:"#hjzl_57.png"},
					{img:"#hjzl_58.png"},
					//					{img:"#res/bg/hjzl/hjzl_59.png"},
					{img:"#hjzl_60.png"},	
					{img:"#hjzl_61.png"},
					{img:"#hjzl_62.png"},
					{img:"#hjzl_63.png"},
					{img:"#hjzl_64.png"},
					{img:"#hjzl_66.png"},
					{img:"#hjzl_67.png"},
					{img:"#hjzl_68.png"},
					{img:"#hjzl_69.png"},
					{img:"#hjzl_70.png"},
					{img:"#hjzl_71.png"},
                ],         
                [          
					{img:"#hjzl_74.png"},
					{img:"#hjzl_75.png"},
					{img:"#hjzl_76.png"},
					{img:"#hjzl_77.png"},
					{img:"#hjzl_78.png"},
					{img:"#hjzl_79.png"},
					{img:"#hjzl_80.png"},
                    {img:"#hjzl_brokengate.png"},
                    {img:"#hjzl_brokengate2.png"}, 
                ],
            ],
        },
        {   name:"HLG",
            plist:"res/background_cn/",
            fore:{img:"res/bg/hlg/hlg_fore.png",pos:cc.p(0,385)},
            back:{img:"res/bg/hlg/hlg_sky.png",pos:cc.p(0,385)},
			lists:[  
				[
					{img:"#hlg_1.png"},
					{img:"#hlg_2.png"},
					// {img:"#hlg_3.png"},
					// {img:"#hlg_4.png"},
					// {img:"#hlg_6.png"},
					// {img:"#hlg_7.png"},
					// {img:"#hlg_8.png"},
					{img:"#hlg_10.png"},
					// {img:"#hlg_11.png"},
					{img:"#hlg_12.png"},	
					{img:"#hlg_13.png"},
					// {img:"#hlg_14.png"},
					// {img:"#hlg_15.png"},
					{img:"#hlg_16.png"},
					{img:"#hlg_17.png"},
					{img:"#hlg_18.png"},
					{img:"#hlg_19.png"},
					{img:"#hlg_20.png"},
					{img:"#hlg_21.png"},
					{img:"#hlg_22.png"},
					{img:"#hlg_23.png"},
					{img:"#hlg_24.png"},	
    			],     
                [     
					{img:"#hlg_25.png"},
					{img:"#hlg_26.png"},
					// {img:"#hlg_27.png"},
					// {img:"#hlg_28.png"},
					// {img:"#res/bg/hlg/hlg_29.png"},
					// {img:"#hlg_30.png"},
					{img:"#hlg_31.png"},
					{img:"#hlg_32.png"},
					// {img:"#hlg_33.png"},
					// {img:"#hlg_34.png"},
					{img:"#hlg_35.png"},
					// {img:"#hlg_36.png"},	
					// {img:"#hlg_37.png"},
					{img:"#hlg_38.png"},
					{img:"#hlg_39.png"},
					{img:"#hlg_40.png"},
					{img:"#hlg_41.png"},
					{img:"#hlg_42.png"},
					{img:"#hlg_43.png"},
					{img:"#hlg_44.png"},
					{img:"#hlg_45.png"},
					{img:"#hlg_46.png"},
					{img:"#hlg_47.png"},
					{img:"#hlg_48.png"},	
                ],         
                [          
					{img:"#hlg_49.png"},
					{img:"#hlg_50.png"},
					// {img:"#hlg_51.png"},
					{img:"#hlg_52.png"},
					{img:"#hlg_53.png"},
					// {img:"#hlg_54.png"},
					{img:"#hlg_55.png"},
					{img:"#hlg_56.png"},
					{img:"#hlg_57.png"},
					{img:"#hlg_58.png"},
					{img:"#hlg_59.png"},
					{img:"#hlg_60.png"},	
					{img:"#hlg_61.png"},
					{img:"#hlg_62.png"},
					{img:"#hlg_63.png"},
					{img:"#hlg_64.png"},
					{img:"#hlg_65.png"},
					{img:"#hlg_66.png"},
					{img:"#hlg_67.png"},
					{img:"#hlg_68.png"},
					{img:"#hlg_69.png"},
					{img:"#hlg_70.png"},
					{img:"#hlg_71.png"},
					// {img:"#hlg_72.png"},	
                ],         
                [          
					{img:"#hlg_73.png"},
					{img:"#hlg_74.png"},
					// {img:"#hlg_75.png"},
					{img:"#hlg_76.png"},
					{img:"#hlg_77.png"},
                    {img:"#hlg_brokengate.png"},
                    {img:"#hlg_brokengate2.png"},
                    {img:"#hlg_brokengate3.png"},
                    {img:"#hlg_brokengate4.png"},
                     {img:"#hlg_brokengate5.png"},
                     {img:"#hlg_brokengate6.png"},
                  {img:"#hlg_brokengate7.png"},
                ],
    		],
        },
        {   
        	name:"TEST",
            plist:"res/background_cn/",
            fore:{img:"res/bg/hlg/hlg_fore.png",pos:cc.p(0,385)},
            back:{img:"res/bg/hlg/hlg_sky.png",pos:cc.p(0,385)},
			lists:[  
				[
					{img:"res/bg/forest/background1.png"}, 
					{img:"res/bg/forest/background2.png"}, 
					{img:"res/bg/forest/background3.png"}, 
					{img:"res/bg/forest/background4.png"}, 
    			],     
                [   
                	{ img: "res/bg/forest/mbground1.png"},
				    { img: "res/bg/forest/mbground2.png"},
			        { img: "res/bg/forest/mbground3.png"}, 
			        { img: "res/bg/forest/mbground4.png"},
			        { img: "res/bg/forest/mbground5.png"},
                ],         
                [          
					{ img: "res/bg/forest/middleground1.png"},
					{ img: "res/bg/forest/middleground1.png"},
					{ img: "res/bg/forest/middleground1.png"}, 
					{ img: "res/bg/forest/fmground1.png"}, 
	    			{ img: "res/bg/forest/fmground2.png"},
	    			{ img: "res/bg/forest/fmground1.png"},
                ],         
                [          
					{ img: "res/bg/forest/foreground1.png"},
			    	{ img: "res/bg/forest/foreground2.png"},
			        { img: "res/bg/forest/foreground3.png"},
			        { img: "res/bg/forest/foreground4.png"},
				    { img: "res/bg/forest/foreground5.png"},
                ],
    		],
        },
    ]